purge_purger_http.settings.*:
  type: config_entity
  label: 'HTTP Purger'
  mapping:
    id:
      type: string
      translatable: false
    name:
      type: string
      translatable: false
    invalidationtype:
      type: string
      translatable: false
    hostname:
      type: string
      translatable: false
    port:
      type: integer
      translatable: false
    path:
      type: string
      translatable: false
    request_method:
      type: string
      translatable: false
    scheme:
      type: string
      translatable: false
    verify:
      type: string
      translatable: false
    timeout:
      type: float
      translatable: false
    connect_timeout:
      type: float
      translatable: false
    cooldown_time:
      type: float
      translatable: false
    max_requests:
      type: integer
      translatable: false
